package shared

import "errors"

// Sentinel errors for validation and lifecycle checks.
var (
	ErrNotInitialized       = errors.New("mcp server is not initialized")
	ErrHubNotConfigured     = errors.New("federation hub is not configured")
	ErrHubNotInitialized    = errors.New("federation hub is not initialized")
	ErrHubAlreadyInit       = errors.New("federation hub is already initialized")
	ErrHubShutDown          = errors.New("federation hub is shut down")
	ErrContextRequired      = errors.New("context is required")
	ErrReaderRequired       = errors.New("reader is required")
	ErrWriterRequired       = errors.New("writer is required")
	ErrHostRequired         = errors.New("host is required")
	ErrPayloadRequired      = errors.New("payload is required")
	ErrSwarmIDRequired      = errors.New("swarmId is required")
	ErrSourceSwarmRequired  = errors.New("sourceSwarmId is required")
	ErrTargetSwarmRequired  = errors.New("targetSwarmId is required")
	ErrProposerRequired     = errors.New("proposerId is required")
	ErrProposalIDRequired   = errors.New("proposalId is required")
	ErrProposalTypeRequired = errors.New("proposalType is required")
	ErrVoterRequired        = errors.New("voterId is required")
	ErrValueRequired        = errors.New("value is required")
	ErrAgentIDRequired      = errors.New("agentId is required")
	ErrTypeRequired         = errors.New("type is required")
	ErrTaskRequired         = errors.New("task is required")
	ErrNameRequired         = errors.New("name is required")
	ErrMaxAgentsRequired    = errors.New("maxAgents must be greater than 0")
	ErrStdioNotConfigured   = errors.New("stdio transport server is not configured")
	ErrTTLRequired          = errors.New("ttl must be greater than 0")
	ErrQuorumRange          = errors.New("consensus quorum must be between 0 and 1")
	ErrProposalTimeout      = errors.New("proposal timeout must be greater than 0")
	ErrProposalTimeoutRange = errors.New("proposal timeout is out of range")
	ErrInvalidPort          = errors.New("invalid port")
	ErrSamplingReqRequired  = errors.New("sampling request is required")
	ErrSessionSaveRequired  = errors.New("session save request is required")
	ErrLogManagerRequired   = errors.New("log manager is required")
)
